[build]
  base = "exampleSite"
  publish = "public"

    [build.environment]
      HUGO_VERSION = "0.144.2"
      HUGO_ENABLEGITINFO = "true"

[context.production]
  command = "hugo --theme repo --themesDir ../.. --baseURL ${URL} --gc --minify"

  [context.production.environment]
    HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo --theme repo --themesDir ../.. --baseURL $DEPLOY_PRIME_URL --gc --minify --buildDrafts"

[context.branch-deploy]
  command = "hugo --theme repo --themesDir ../.. --baseURL $DEPLOY_PRIME_URL --gc --minify"
