version: 2.1

executors:
  hugo:
    parameters:
      version:
        description: "version tag"
        type: string
    docker:
      - image: cibuilds/hugo:<<parameters.version>>

jobs:
  build-check:
    parameters:
      version:
        description: "version tag"
        type: string
    executor:
      name: hugo
      version: <<parameters.version>>
    working_directory: ~/LoveIt
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run: hugo --source exampleSite --gc --minify --environment production
      - run: htmlproofer exampleSite/public --disable-external true --ignore-missing-alt true

workflows:
  build-check:
    jobs:
      - build-check:
          name: build-check
          matrix:
            parameters:
              version:
                - 0.144.0
                - 0.128.0
