version: 2.1
jobs:
  build-check:
    docker:
      - image: cibuilds/hugo:0.128.0
    working_directory: ~/LoveIt
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run: hugo --source=exampleSite -v --gc
      - run: htmlproofer exampleSite/public --disable-external true

workflows:
  build-check-exampleSite:
    jobs:
      - build-check
