baseURL = "/"
# website language
languageCode = "en"
# [en, zh, ...] determines which i18n file to use
defaultContentLanguage = "en"
# website title
title = "LoveIt Theme"
# theme
theme = "LoveIt"
# whether to use git commit log to generate lastmod record
enableGitInfo = false
# whether to include chinese/japanese/korean
hasCJKLanguage = false
# default amount of posts in each pages
paginate = 12
# whether to use emoji code
enableEmoji = true
# whether to use robots.txt
enableRobotsTXT = true
# [UA-XXXXXXXX-X] google analytics code
googleAnalytics = ""
# copyright description used only for seo schema
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."
# date format
dateFormatToUse = "2006-01-02"

# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
    style = "monokai"
    tabWidth = 4
  # Goldmark is from Hugo 0.60 the default library used for Markdown
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.renderer]
      # whether to use HTML tags directly in the document
      unsafe = true
  # Table Of Contents settings
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 6

# Author Info
[author]
  name = "xxxx"
  link = ""

# Sitemap Info
[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

# Permalinks Info (https://gohugo.io/content-management/urls/#permalinks)
[Permalinks]
  posts = ":year/:month/:filename"

# Menu Info
[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "posts"
    weight = 1

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "tags"
    weight = 2

  [[menu.main]]
    identifier = "categories"
    name = "Categories"
    url = "categories"
    weight = 3

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "about"
    weight = 4

  [[menu.main]]
    identifier = "zh"
    pre = '<i class="fas fa-language fa-fw"></i>'
    name = ""
    title = "简体中文"
    url = "https://hugo-loveit-zh.netlify.com"
    weight = 5

[params]
  # LoveIt theme version
  version = "0.1.X"
  # site description
  description = "About LoveIt Theme"
  # site keywords
  keywords = ["Theme", "Hugo"]
  # site default theme ("light", "dark", "auto")
  defaultTheme = "auto"
  # public git repo url to link lastmod git commit only then enableGitInfo is true
  gitRepo = ""

  # Header info
  [params.header]
    # desktop header mode ("fixed", "normal", "auto")
    desktopMode = "fixed"
    # mobile header mode ("fixed", "normal", "auto")
    mobileMode = "auto"

  # Footer Copyright Info
  [params.footer]
    # Site creation time
    since = 2019
    # ICP info only in China (HTML format is allowed)
    icp = ""
    # license info (HTML format is allowed)
    license= '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

  # Home Page Info
  [params.home]
    # Home Page Profile
    [params.home.profile]
      enable = true
      # Gravatar Email for preferred avatar in home page
      gravatarEmail = ""
      # URL of avatar shown in home page
      avatarURL = "images/avatar.png"
      # subtitle shown in home page
      subtitle = "A Clean, Elegant but Advanced Hugo Theme"
      # whether to use typeit animation for subtitle
      typeit = true
      # whether to show social links
      social = true
    # Home Page Posts
    [params.home.posts]
      enable = true
      # special amount of posts in each home posts page
      paginate = 6
      # default behavior when you don't set "hiddenFromHomePage" in front matter
      defaultHiddenFromHomePage = false

  # Social Info in home page
  [params.social]
    GitHub = "xxxx"
    Linkedin = "xxxx"
    Twitter = "xxxx"
    #Instagram = "xxxx"
    Email = "xxxx@outlook.com"
    Facebook = "xxxx"
    Telegram = "xxxx"
    #Medium = "xxxx"
    #Gitlab = "xxxx"
    #Youtubelegacy = "xxxx"
    #Youtubecustom = "xxxx"
    #Youtubechannel = "xxxx"
    #Tumblr ="xxxx"
    #Quora = "xxxx"
    #Keybase = "xxxx"
    #Pinterest = "xxxx"
    #Reddit = "xxxx"
    #Codepen = "xxxx"
    #FreeCodeCamp = "xxxx"
    #Bitbucket = "xxxx"
    #Stackoverflow = "xxxx"
    #Weibo = "xxxx"
    #Odnoklassniki = "xxxx"
    #VKontakte = "xxxx"
    #Flickr = "xxxx"
    #Xing = "xxxx"
    #Snapchat = "xxxx"
    #Soundcloud = "xxxx"
    #Spotify = "xxxx"
    #Bandcamp = "xxxx"
    #Paypal = "xxxx"
    #Fivehundredpx = "xxxx"
    #Mix = "xxxx"
    #Goodreads = "xxxx"
    #Lastfm = "xxxx"
    #Foursquare = "xxxx"
    #Hackernews = "xxxx"
    #Kickstarter = "xxxx"
    #Patreon = "xxxx"
    #Steam = "xxxx"
    #Twitch = "xxxx"
    #Strava = "xxxx"
    #Skype = "xxxx"
    #Whatsapp = "xxxx"
    #Zhihu = "xxxx"
    #Douban = "xxxx"
    #Angellist = "xxxx"
    #Slidershare = "xxxx"
    #Jsfiddle = "xxxx"
    #Deviantart = "xxxx"
    #Behance = "xxxx"
    #Dribble = "xxxx"
    #Wordpress = "xxxx"
    #Vine = "xxxx"
    #Googlescholar = "xxxx"
    #Researchgate = "xxxx"
    #Mastodon = "xxxx"
    #MastodonPrefix = "https://mastodon.technology/"
    #Thingiverse = "xxxx"
    #Devto = "xxxx"
    #Gitea = "xxxx"
    #XMPP = "xxxx"
    #Matrix ="xxxx"
    #Bilibili = ""

  # Page config
  [params.page]
    # whether to show social share links in post page
    socialShare = true
    # whether to show link to Raw Markdown content of the post
    linkToMarkdown = true

  # Social Share Links in post page
  [params.share]
    enable = true
    Twitter = true
    Facebook = true
    Reddit = true
    #Linkedin = true
    #Pinterest = true
    #HackerNews = true
    #Mix = true
    #Tumblr = true
    #VKontakte = true
    #Weibo = true

  # mathematical formulas (KaTeX)
  [params.math]
    enable = true
    blockLeftDelimiter = ""
    blockRightDelimiter = ""
    inlineLeftDelimiter = "$"
    inlineRightDelimiter = "$"
    # KaTeX extension copy_tex
    copyTex = true
    # KaTeX extension mhchem
    mhchem = true

  # CSS and JS Files CDN
  [params.cdn]
    ## for example '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.10.1/css/all.min.css" integrity="sha256-fdcFNFiBMrNfWL6OcAGQz6jDgNTRxnrLEd4vJYFWScE=" crossorigin="anonymous">'
    fontawesomeFreeCSS = ''
    animateCSS = ''
    gitalkCSS = ''
    gitalkJS = ''
    valineJS = ''
    lazysizesJS = ''
    smoothScrollJS = ''
    katexCSS = ''
    katexJS = ''
    katexAutoRenderJS = ''
    katexCopyTexCSS = ''
    katexCopyTexJS = ''
    katexMhchemJS = ''
    mermaidJS = ''
    echartsJS = ''
    echartsMacaronsJS = ''
    typeitJS = ''
    aplayerCSS = ''
    aplayerJS = ''
    metingJS = ''

  # site verification code for Google/Bing/Yandex/Pinterest/Baidu
  [params.verification]
    google = ""
    bing = ""
    yandex = ""
    pinterest = ""
    baidu = ""

  # Publisher Info just for SEO
  [params.publisher]
    name = "xxxx"
    [params.publisher.logo]
      url = "logo.png"
      width = 127
      height = 40

  # Website Log Info just for SEO
  [params.logo]
    url = "logo.png"
    width = 127
    height = 40

  # Website Image Info just for SEO
  [params.image]
    url = "cover.png"
    width = 800
    height = 600

  # Comment Config
  [params.comment]
    enable = true

    # Disqus Comment Config (https://disqus.com/)
    [params.comment.disqus]
      # Disqus shortname to use Disqus in posts
      shortname = "dillonzq"

    # Gittalk Comment Config (https://github.com/gitalk/gitalk)
    [params.comment.gitalk]
      owner = ""
      repo = ""
      clientId = ""
      clientSecret = ""

    # Valine Comment Config (https://github.com/xCss/Valine)
    [params.comment.valine]
      enable = false
      appId = ""
      appKey = ""
      placeholder = "Your comment ..."
      notify = false
      verify = true
      avatar = "mp"
      #meta= ""
      pageSize = 10
      visitor = true
      recordIP = true

    # Facebook Comment Config (https://developers.facebook.com/docs/plugins/comments)
    [params.comment.facebook]
      enable = false
      width = "100%"
      numPosts = 10
      appId = ""
      languageCode = "en_US"

# Privacy Info (https://gohugo.io/about/hugo-and-gdpr/)
[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true

  [privacy.youtube]
    privacyEnhanced = true

# Options to make output .md files
[mediaTypes]
  [mediaTypes."text/plain"]
    suffixes = ["md"]

# Options to make output .md files
[outputFormats.MarkDown]
  mediaType = "text/plain"
  isPlainText = true
  isHTML = false

# Options to make hugo output files
[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML", "MarkDown"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  taxonomyTerm = ["HTML"]
