[build]
  command = "hugo"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.57"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production hugo --gc --minify"
